# Generated by Django 3.2.9 on 2022-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='alreadyLiked',
            new_name='Liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
