# Generated by Django 3.2.9 on 2022-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220314_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='Liked',
        ),
        migrations.AlterField(
            model_name='like',
            name='dislikes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
