# Generated by Django 3.2.9 on 2022-03-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='dislikes',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
