# Generated by Django 3.2.9 on 2022-07-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220314_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
